import { describe, expect, it } from '@jest/globals';
import { generateCode } from '../CodeGenerator';
import type { JoinState } from '../types/joinState';

const USERS_TABLE = {
	name: 'df_users',
	columns: [
		{ name: 'id', dtype: 'int64', nullable: false },
		{ name: 'name', dtype: 'object', nullable: false },
	],
};

const ORDERS_TABLE = {
	name: 'df_orders',
	columns: [
		{ name: 'order_id', dtype: 'int64', nullable: false },
		{ name: 'user_id', dtype: 'int64', nullable: false },
		{ name: 'total', dtype: 'float64', nullable: false },
	],
};

function buildBasePandasState(): JoinState {
	return {
		dialect: 'pandas',
		outputName: 'result_df',
		tables: [USERS_TABLE, ORDERS_TABLE],
		joins: [
			{
				id: 'e1',
				leftTable: 'df_users',
				leftColumn: 'id',
				rightTable: 'df_orders',
				rightColumn: 'user_id',
				joinType: 'left',
			},
		],
		selectedColumns: [
			{ table: 'df_users', column: 'id', alias: null },
			{ table: 'df_users', column: 'name', alias: null },
			{ table: 'df_orders', column: 'total', alias: 'order_total' },
		],
	};
}

describe('CodeGenerator', () => {
	it('Case 1: generates single left join Pandas code', () => {
		const state = buildBasePandasState();
		const result = generateCode(state);

		expect(result).toBe(`# Generated by Visual Join Builder
result_df = df_users.merge(
    df_orders,
    how='left',
    left_on='id',
    right_on='user_id'
)
result_df = result_df[['id', 'name', 'total']]
result_df = result_df.rename(columns={'total': 'order_total'})`);
	});

	it('Case 2: omits column filter when selectedColumns is empty', () => {
		const state: JoinState = {
			...buildBasePandasState(),
			joins: [{ ...buildBasePandasState().joins[0], joinType: 'inner' }],
			selectedColumns: [],
		};

		const result = generateCode(state);
		expect(result).toBe(`# Generated by Visual Join Builder
result_df = df_users.merge(
    df_orders,
    how='inner',
    left_on='id',
    right_on='user_id'
)`);
	});

	it('Case 3: adds collision suffixes in Pandas merge', () => {
		const state: JoinState = {
			...buildBasePandasState(),
			selectedColumns: [],
			tables: [
				{
					name: 'df_users',
					columns: [
						{ name: 'id', dtype: 'int64', nullable: false },
						{ name: 'created_at', dtype: 'datetime64[ns]', nullable: false },
					],
				},
				{
					name: 'df_orders',
					columns: [
						{ name: 'user_id', dtype: 'int64', nullable: false },
						{ name: 'created_at', dtype: 'datetime64[ns]', nullable: false },
					],
				},
			],
		};

		const result = generateCode(state);
		expect(result).toBe(`# Generated by Visual Join Builder
# NOTE: Column name collision detected: created_at
result_df = df_users.merge(
    df_orders,
    how='left',
    left_on='id',
    right_on='user_id',
    suffixes=('_users', '_orders')
)`);
	});

	it('Case 4: resolves chained joins in topological order', () => {
		const state: JoinState = {
			dialect: 'pandas',
			outputName: 'result_df',
			tables: [
				{ name: 'df_a', columns: [{ name: 'id', dtype: 'int64', nullable: false }] },
				{
					name: 'df_b',
					columns: [
						{ name: 'id', dtype: 'int64', nullable: false },
						{ name: 'a_id', dtype: 'int64', nullable: false },
					],
				},
				{ name: 'df_c', columns: [{ name: 'b_id', dtype: 'int64', nullable: false }] },
			],
			joins: [
				{
					id: 'e1',
					leftTable: 'df_a',
					leftColumn: 'id',
					rightTable: 'df_b',
					rightColumn: 'a_id',
					joinType: 'inner',
				},
				{
					id: 'e2',
					leftTable: 'df_b',
					leftColumn: 'id',
					rightTable: 'df_c',
					rightColumn: 'b_id',
					joinType: 'left',
				},
			],
			selectedColumns: [],
		};

		const result = generateCode(state);
		expect(result).toBe(`# Generated by Visual Join Builder
_step1 = df_a.merge(
    df_b,
    how='inner',
    left_on='id',
    right_on='a_id'
)
result_df = _step1.merge(
    df_c,
    how='left',
    left_on='id',
    right_on='b_id'
)`);
	});

	it('Case 5: generates Pandas cross join', () => {
		const state: JoinState = {
			dialect: 'pandas',
			outputName: 'result_df',
			tables: [
				{ name: 'df_a', columns: [{ name: 'id', dtype: 'int64', nullable: false }] },
				{ name: 'df_b', columns: [{ name: 'a_id', dtype: 'int64', nullable: false }] },
			],
			joins: [
				{
					id: 'e1',
					leftTable: 'df_a',
					leftColumn: 'id',
					rightTable: 'df_b',
					rightColumn: 'a_id',
					joinType: 'cross',
				},
			],
			selectedColumns: [],
		};

		const result = generateCode(state);
		expect(result).toBe(`# Generated by Visual Join Builder
result_df = df_a.merge(df_b, how='cross')`);
	});

	it('Case 6: emits type mismatch warning and cast in Pandas', () => {
		const state: JoinState = {
			...buildBasePandasState(),
			selectedColumns: [],
			tables: [
				{
					name: 'df_users',
					columns: [
						{ name: 'id', dtype: 'object', nullable: false },
						{ name: 'name', dtype: 'object', nullable: false },
					],
				},
				{
					name: 'df_orders',
					columns: [
						{ name: 'order_id', dtype: 'int64', nullable: false },
						{ name: 'user_id', dtype: 'int64', nullable: false },
						{ name: 'total', dtype: 'float64', nullable: false },
					],
				},
			],
		};

		const result = generateCode(state);
		expect(result).toBe(`# Generated by Visual Join Builder
# WARNING: Type mismatch on join key — df_orders.user_id is int64, df_users.id is object
# Casting df_orders.user_id to object to match
df_orders = df_orders.copy()
df_orders['user_id'] = df_orders['user_id'].astype(object)
result_df = df_users.merge(
    df_orders,
    how='left',
    left_on='id',
    right_on='user_id'
)`);
	});

	it('Case 7: generates DuckDB SQL with duckdb.sql(query).df()', () => {
		const state: JoinState = {
			...buildBasePandasState(),
			dialect: 'duckdb',
		};

		const result = generateCode(state);
		expect(result).toBe(`# Generated by Visual Join Builder
import duckdb

query = """
SELECT
    df_users.id,
    df_users.name,
    df_orders.total AS order_total
FROM df_users
LEFT JOIN df_orders ON df_users.id = df_orders.user_id
"""
result_df = duckdb.sql(query).df()`);
	});

	it('Case 8: generates PySpark join/select chain', () => {
		const state: JoinState = {
			...buildBasePandasState(),
			dialect: 'pyspark',
		};

		const result = generateCode(state);
		expect(result).toBe(`# Generated by Visual Join Builder
result_df = df_users.join(
    df_orders,
    on=df_users['id'] == df_orders['user_id'],
    how='left'
).select(
    df_users['id'],
    df_users['name'],
    df_orders['total'].alias('order_total')
)`);
	});

	it('Case 9: treats explicit all-column selection like select-all', () => {
		const state: JoinState = {
			...buildBasePandasState(),
			joins: [{ ...buildBasePandasState().joins[0], joinType: 'inner' }],
			selectedColumns: [
				{ table: 'df_users', column: 'id', alias: null },
				{ table: 'df_users', column: 'name', alias: null },
				{ table: 'df_orders', column: 'order_id', alias: null },
				{ table: 'df_orders', column: 'user_id', alias: null },
				{ table: 'df_orders', column: 'total', alias: null },
			],
		};

		const result = generateCode(state);
		expect(result).toBe(`# Generated by Visual Join Builder
result_df = df_users.merge(
    df_orders,
    how='inner',
    left_on='id',
    right_on='user_id'
)`);
	});
});
