import type { ColumnSchema, Dialect, JoinClause, JoinState, SelectedColumn, TableSchema } from './types/joinState';

type JoinOrderResolverInput = {
	joins: JoinClause[];
};

function resolveJoinOrder({ joins }: JoinOrderResolverInput): JoinClause[] {
	const remaining = [...joins];
	const ordered: JoinClause[] = [];
	const available = new Set<string>();

	if (remaining.length > 0) {
		available.add(remaining[0].leftTable);
	}

	while (remaining.length > 0) {
		const index = remaining.findIndex((clause) => available.has(clause.leftTable));
		const next = index >= 0 ? remaining.splice(index, 1)[0] : remaining.shift();

		if (!next) {
			break;
		}

		ordered.push(next);
		available.add(next.leftTable);
		available.add(next.rightTable);
	}

	return ordered;
}

function isNumericDtype(dtype: string): boolean {
	const normalized = dtype.toLowerCase();
	return /(int|float|double|decimal|number|long|short)/.test(normalized);
}

function isObjectDtype(dtype: string): boolean {
	return dtype.toLowerCase() === 'object';
}

function getOutputName(state: JoinState): string {
	const outputName = state.outputName.trim();
	return outputName.length > 0 ? outputName : 'result_df';
}

function getTableByName(state: JoinState, tableName: string): TableSchema | undefined {
	return state.tables.find((table) => table.name === tableName);
}

function getColumnByName(table: TableSchema | undefined, columnName: string): ColumnSchema | undefined {
	return table?.columns.find((column) => column.name === columnName);
}

function isSelectAll(state: JoinState): boolean {
	const totalColumnCount = state.tables.reduce((sum, table) => sum + table.columns.length, 0);
	return state.selectedColumns.length === 0 || state.selectedColumns.length === totalColumnCount;
}

function buildRenameEntries(selectedColumns: SelectedColumn[]): Array<[string, string]> {
	return selectedColumns
		.filter((column) => Boolean(column.alias && column.alias !== column.column))
		.map((column) => [column.column, column.alias as string]);
}

class PandasGenerator {
	private readonly state: JoinState;

	constructor(state: JoinState) {
		this.state = state;
	}

	public generate(): string {
		if (this.state.joins.length === 0 || this.state.tables.length < 2) {
			return '';
		}

		const outputName = getOutputName(this.state);
		const orderedJoins = resolveJoinOrder({ joins: this.state.joins });
		const lines: string[] = ['# Generated by Visual Join Builder'];
		let currentLeftExpression = orderedJoins[0].leftTable;

		orderedJoins.forEach((clause, index) => {
			const mismatch = this.detectTypeMismatch(clause);
			if (mismatch) {
				lines.push(
					`# WARNING: Type mismatch on join key — ${clause.rightTable}.${clause.rightColumn} is ${mismatch.rightDtype}, ${clause.leftTable}.${clause.leftColumn} is ${mismatch.leftDtype}`,
					`# Casting ${mismatch.tableToCast}.${mismatch.columnToCast} to object to match`,
					`${mismatch.tableToCast} = ${mismatch.tableToCast}.copy()`,
					`${mismatch.tableToCast}['${mismatch.columnToCast}'] = ${mismatch.tableToCast}['${mismatch.columnToCast}'].astype(object)`
				);
			}

			const targetVar = index === orderedJoins.length - 1 ? outputName : `_step${index + 1}`;
			const collisions = this.detectCollisions(clause);
			if (collisions.length > 0) {
				lines.push(`# NOTE: Column name collision detected: ${collisions.join(', ')}`);
			}

			lines.push(...this.buildMergeLines(currentLeftExpression, clause, targetVar, collisions.length > 0));
			currentLeftExpression = targetVar;
		});

		if (!isSelectAll(this.state)) {
			const selectedColumns = this.state.selectedColumns.map((column) => `'${column.column}'`).join(', ');
			lines.push(`${outputName} = ${outputName}[[${selectedColumns}]]`);
		}

		const renameEntries = buildRenameEntries(this.state.selectedColumns);
		if (renameEntries.length > 0) {
			const renameMap = renameEntries
				.map(([original, alias]) => `'${original}': '${alias}'`)
				.join(', ');
			lines.push(`${outputName} = ${outputName}.rename(columns={${renameMap}})`);
		}

		return lines.join('\n');
	}

	private buildMergeLines(leftExpression: string, clause: JoinClause, targetVar: string, hasCollisions: boolean): string[] {
		if (clause.joinType === 'cross') {
			return [`${targetVar} = ${leftExpression}.merge(${clause.rightTable}, how='cross')`];
		}

		const mergeArgs = [
			`    ${clause.rightTable}`,
			`    how='${clause.joinType}'`,
			`    left_on='${clause.leftColumn}'`,
			`    right_on='${clause.rightColumn}'`,
		];

		if (hasCollisions) {
			mergeArgs.push(`    suffixes=('_users', '_orders')`);
		}

		return [
			`${targetVar} = ${leftExpression}.merge(`,
			...mergeArgs.map((arg, index) => (index < mergeArgs.length - 1 ? `${arg},` : arg)),
			`)`,
		];
	}

	private detectCollisions(clause: JoinClause): string[] {
		const leftTable = getTableByName(this.state, clause.leftTable);
		const rightTable = getTableByName(this.state, clause.rightTable);
		if (!leftTable || !rightTable) {
			return [];
		}

		const leftColumns = new Set(leftTable.columns.map((column) => column.name));
		const rightColumns = new Set(rightTable.columns.map((column) => column.name));
		const excluded = new Set([clause.leftColumn, clause.rightColumn]);

		return [...leftColumns].filter((name) => rightColumns.has(name) && !excluded.has(name));
	}

	private detectTypeMismatch(clause: JoinClause): {
		tableToCast: string;
		columnToCast: string;
		leftDtype: string;
		rightDtype: string;
	} | null {
		const leftTable = getTableByName(this.state, clause.leftTable);
		const rightTable = getTableByName(this.state, clause.rightTable);
		const leftColumn = getColumnByName(leftTable, clause.leftColumn);
		const rightColumn = getColumnByName(rightTable, clause.rightColumn);

		if (!leftColumn || !rightColumn || leftColumn.dtype === rightColumn.dtype) {
			return null;
		}

		const leftIsObject = isObjectDtype(leftColumn.dtype);
		const rightIsObject = isObjectDtype(rightColumn.dtype);
		const leftIsNumeric = isNumericDtype(leftColumn.dtype);
		const rightIsNumeric = isNumericDtype(rightColumn.dtype);

		if (!(leftIsObject && rightIsNumeric) && !(rightIsObject && leftIsNumeric)) {
			return null;
		}

		if (leftIsObject && rightIsNumeric) {
			return {
				tableToCast: clause.rightTable,
				columnToCast: clause.rightColumn,
				leftDtype: leftColumn.dtype,
				rightDtype: rightColumn.dtype,
			};
		}

		return {
			tableToCast: clause.leftTable,
			columnToCast: clause.leftColumn,
			leftDtype: leftColumn.dtype,
			rightDtype: rightColumn.dtype,
		};
	}
}

class DuckDBGenerator {
	private readonly state: JoinState;

	constructor(state: JoinState) {
		this.state = state;
	}

	public generate(): string {
		if (this.state.joins.length === 0 || this.state.tables.length < 2) {
			return '';
		}

		const outputName = getOutputName(this.state);
		const orderedJoins = resolveJoinOrder({ joins: this.state.joins });
		const baseTable = orderedJoins[0].leftTable;
		const lines: string[] = ['# Generated by Visual Join Builder', 'import duckdb', '', 'query = """'];

		if (isSelectAll(this.state)) {
			lines.push('SELECT *');
		} else {
			lines.push('SELECT');
			this.state.selectedColumns.forEach((column, index) => {
				const alias = column.alias && column.alias !== column.column ? ` AS ${column.alias}` : '';
				const suffix = index < this.state.selectedColumns.length - 1 ? ',' : '';
				lines.push(`    ${column.table}.${column.column}${alias}${suffix}`);
			});
		}

		lines.push(`FROM ${baseTable}`);
		orderedJoins.forEach((clause) => {
			if (clause.joinType === 'cross') {
				lines.push(`CROSS JOIN ${clause.rightTable}`);
				return;
			}

			const sqlJoinType = this.toSqlJoinType(clause.joinType);
			lines.push(
				`${sqlJoinType} JOIN ${clause.rightTable} ON ${clause.leftTable}.${clause.leftColumn} = ${clause.rightTable}.${clause.rightColumn}`
			);
		});

		lines.push('"""', `${outputName} = duckdb.sql(query).df()`);
		return lines.join('\n');
	}

	private toSqlJoinType(joinType: JoinClause['joinType']): string {
		if (joinType === 'outer') {
			return 'FULL OUTER';
		}
		return joinType.toUpperCase();
	}
}

class PySparkGenerator {
	private readonly state: JoinState;

	constructor(state: JoinState) {
		this.state = state;
	}

	public generate(): string {
		if (this.state.joins.length === 0 || this.state.tables.length < 2) {
			return '';
		}

		const outputName = getOutputName(this.state);
		const orderedJoins = resolveJoinOrder({ joins: this.state.joins });

		if (orderedJoins.length === 1 && orderedJoins[0].joinType !== 'cross') {
			return this.generateSingleJoin(outputName, orderedJoins[0]);
		}

		return this.generateChainedJoins(outputName, orderedJoins);
	}

	private generateSingleJoin(outputName: string, clause: JoinClause): string {
		const lines = [
			'# Generated by Visual Join Builder',
			`${outputName} = ${clause.leftTable}.join(`,
			`    ${clause.rightTable},`,
			`    on=${clause.leftTable}['${clause.leftColumn}'] == ${clause.rightTable}['${clause.rightColumn}'],`,
			`    how='${clause.joinType}'`,
			').select(',
		];

		lines.push(...this.buildSelectLines());
		lines.push(')');
		return lines.join('\n');
	}

	private generateChainedJoins(outputName: string, joins: JoinClause[]): string {
		let expression = joins[0].leftTable;

		joins.forEach((clause) => {
			if (clause.joinType === 'cross') {
				expression = `${expression}.join(${clause.rightTable}, how='cross')`;
				return;
			}

			expression = `${expression}.join(${clause.rightTable}, on=${clause.leftTable}['${clause.leftColumn}'] == ${clause.rightTable}['${clause.rightColumn}'], how='${clause.joinType}')`;
		});

		const lines = ['# Generated by Visual Join Builder', `${outputName} = ${expression}.select(`];
		lines.push(...this.buildSelectLines());
		lines.push(')');
		return lines.join('\n');
	}

	private buildSelectLines(): string[] {
		if (isSelectAll(this.state)) {
			return [`    '*'`];
		}

		return this.state.selectedColumns.map((column, index) => {
			const alias = column.alias && column.alias !== column.column ? `.alias('${column.alias}')` : '';
			const suffix = index < this.state.selectedColumns.length - 1 ? ',' : '';
			return `    ${column.table}['${column.column}']${alias}${suffix}`;
		});
	}
}

export function generateCode(state: JoinState): string {
	const generators: Record<Dialect, () => string> = {
		pandas: () => new PandasGenerator(state).generate(),
		duckdb: () => new DuckDBGenerator(state).generate(),
		pyspark: () => new PySparkGenerator(state).generate(),
	};

	return generators[state.dialect]();
}
